### ISSUE TITLE
Instrumenting JDBC connections independently from Tomcat

### ISSUE THREAD

**Issue by aleksandersumowski** [aws/aws-xray-sdk-java#15]
Hi, partially a question, partially feature request: whats currently the recommended way to instrument JDBC connections not running on Tomcat? Custom segments? 

Any thoughts on if it's possible to  provide this functionality in the SDK without depending on Tomcat?

**Comment by haotianw465** [comment]
Hi @softprops @aleksandersumowski,

Thank you for your feedback. Currently the SQL/Postgres support on the SDK is based on tomcat JDBC interceptor. Right now you could manually wrap the database calls with beginSubsegment, endSubsegment and add metadata/annotations to the subsegment to record extra information. For more instrumentation details please refer to this stack overflow question https://stackoverflow.com/questions/49638813/can-i-use-aws-xray-to-trace-mysql-queries-without-tomcat-or-spring.

Having said that, we will definitely look at supporting non-Tomcat JDBC so that the SDK automatically capture all useful information for you. Please let us know which specific package you are using so we can prioritize the work. Any PR is always welcome.

**Comment by aleksandersumowski** [comment]
I'm personally using Postgres in a Clojure project using [clojure.java.jdbc](https://github.com/clojure/java.jdbc) library. I've seen the stackoverflow question but I couldn't find anything like StatementInterceptor for Postgres ...

**Comment by aleksandersumowski** [comment]
also: the programme is doing Kinesis stream processing, so it would be nice to be able to instrument Kinesis Client Library workers - eg starting a segment automatically when a processing of a record begins

**Comment by aleksandersumowski** [comment]
For now it feels that using [datasource-proxy](https://github.com/ttddyy/datasource-proxy) might be the best solution atm

**Comment by haotianw465** [comment]
It looks like `datasource-proxy` is a good option for wrapping queries with begin/end subsegment and adding necessary metadata to it. Please let me know if you still have problem getting it work with X-Ray.

Kinesis support is in our backlog and we will do our best to deliver more features requested by customers. Please stay tuned.

**Comment by joodlehammond** [comment]
FWIW: I found the `TracingDataSource` class in `aws-xray-recorder-sdk-sql` works well if anyone else is here trying to work out how to get this working with Spring.

https://stackoverflow.com/questions/60672795/how-do-i-set-up-aws-x-ray-sql-instrumentation-for-hikari-based-projects-without/60672796#60672796

**Comment by willarmiros** [comment]
Resolved by `aws-xray-recorder-sdk-sql` module released in v2.4.0.
