### ISSUE TITLE
Documentation or link for all sampling rules via json file

### ISSUE THREAD

**Issue by kbradl16** [aws/aws-xray-sdk-java#188]
I see the following snippet from https://docs.aws.amazon.com/xray/latest/devguide/xray-sdk-java-configuration.html#xray-sdk-java-configuration-sampling but this page refers to the options without the "_" https://docs.aws.amazon.com/xray/latest/devguide/xray-console-sampling.html#xray-console-sampling-options

Where should we be looking to correctly configure our sampling.json file(s)? And see what options are supported with Java
```
{
  "version": 2,
  "rules": [
    {
      "description": "Player moves.",
      "host": "*",
      "http_method": "*",
      "url_path": "/api/move/*",
      "fixed_target": 0,
      "rate": 0.05
    }
  ],
  "default": {
    "fixed_target": 1,
    "rate": 0.1
  }
}
```

**Comment by willarmiros** [comment]
Hi @kbradl16,

There are two different types of sampling for X-Ray. *Centralized sampling* is what the second link refers to, it is where you define your sampling rules on the X-Ray console as described by that second link. It is the default type of sampling performed by the Java SDK (and all other SDKs) and strongly recommended, because it allows you to control your sampling rules from a central location, and can apply the rules correctly over all instances in a region.

*Localized sampling* is when you instead define your sampling rules in a JSON file that's packaged with your project. You must opt-in to local sampling by building your recorder with a new `LocalizedSamplingStrategy` pointing to your JSON file. Unless for some reason this SDK will not be able to poll the X-Ray centralized sampling rules, then I would encourage you to manage all your sampling rules on the X-Ray Console.
