### ISSUE TITLE
Add configuration option to create traceIds for NoOpSegments

### ISSUE THREAD

**Issue by friscoMad** [aws/aws-xray-sdk-java#238]
The default behavior when a SamplingResponse is NotSampled is to create a NoOpSegment with TraceID.invalid() as the traceId, in our use case we would like the traceId to be created even in that case so it could be propagated to other services.

Our use case is that we are using the traced as part of the context in our logging system and use that to filter all logs from a single request even when they are from different services. (We are currently using openzipkin / brave).

Currently the servletFilter supports reading than passing the traceId if it comes in the header from other services even with Sampled=0.
There is a `beginSegment(String name, TraceID traceId, @Nullable String parentId)` that could be used as a workaround if we wouldn't like to use sampling but there is nothing that could be used with beginSegmentWithSampling().

I propose a new recorder option and the following change:
```
    public Segment beginNoOpSegment() {
        return beginSegment(Segment.noOp(this.forceCreateTrace?TraceID.create():TraceID.invalid(), this));
    }
```
I think that's all it is needed to fully support this new feature.

**Comment by willarmiros** [comment]
Hi @friscoMad,
Thanks for raising this feature request. We'll add it to our backlog and in the meantime we're open to pull requests if you'd like to add this configuration yourself. Are you using one of our provided packages for injecting trace IDs into logs, or are you just manually including the trace ID in your log messages? If the former, you'll also want to make a change to those injection packages, since we only inject trace IDs for sampled segments (e.g. [Log4J code](https://github.com/aws/aws-xray-sdk-java/blob/master/aws-xray-recorder-sdk-log4j/src/main/java/com/amazonaws/xray/log4j/Log4JSegmentListener.java#L81)).

**Comment by friscoMad** [comment]
Sure! I will probably create that pull request as that's a need we have for us and could be needed for others as well.
I did start with your provided Slf4J listener but ended with a custom one as we would like to have the trace ID, segment Id subsegment ID as different context entries to be able to easily filter by trace or segment without needing to parse the string and btw it should be faster faster as there is no string building in the process.
