### ISSUE TITLE
Trace entity is initially null in lambda functions

### ISSUE THREAD

**Issue by ashleymercer** [aws/aws-xray-sdk-java#24]
**Java version:** 1.8.0_141
**SDK version:** 1.11.259

Not sure if this is a bug or more an "undocumented behaviour": when invoking a Java lambda function, it looks like the lambda infrastructure creates a top-level Segment (in fact, it creates two: one with resource type `AWS::Lamda` to track the whole invocation, and another of type `AWS::Lambda::Function`, to cover the time spent in user code). This is all expected according to e.g. the [examples in the documentation](https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html).

However, I was surprised that neither trace entity is set on the global recorder. This is surprising since I'd expect to find the `AWS::Lambda::Function` entity there, since it's really the "current" trace entity at this point.

```
public class EntityCheck {
  public void checkEntity(Context context) {
    // This returns null
    Entity traceEntity = AWSXRay.getTraceEntity()
  }
}
```

`LambdaSegmentContext` works around this by [explicitly checking for null](https://github.com/aws/aws-xray-sdk-java/blob/master/aws-xray-recorder-sdk-core/src/main/java/com/amazonaws/xray/contexts/LambdaSegmentContext.java#L40), and the [Java tracing documentation](https://docs.aws.amazon.com/lambda/latest/dg/java-tracing.html) gives an example which directly uses subsegments - but the documentation doesn't state that using Segments is forbidden, or explain why this works as it does.

At the very least, might it be worth adding something to the documentation like "only ever use subsegments in lambda functions"?

**Comment by luluzhao** [comment]
Hello @ashleymercer ,

X-Ray SDK can only be used to create `Subsegment` inside Lambda function and these two segments which has resource type `AWS::Lambda` and `AWS::Lambda::Function` are generated by Lambda. Customer shouldn't use X-Ray SDK to create `Segment` inside Lambda function. How Lambda integration works is that we create a `FacadeSegment` which contains `TraceHeader` [information](https://github.com/aws/aws-xray-sdk-java/blob/master/aws-xray-recorder-sdk-core/src/main/java/com/amazonaws/xray/contexts/LambdaSegmentContext.java#L44) and then set the [traceEntity](https://github.com/aws/aws-xray-sdk-java/blob/master/aws-xray-recorder-sdk-core/src/main/java/com/amazonaws/xray/contexts/LambdaSegmentContext.java#L50). Then X-Ray SDK uses facade segment as parent segment in order to generate subsegments and it never emit the facade segment. What is more, X-Ray SDK doesn't have access to the lambda segment. SDK and Lambda container send trace data separately and the X-Ray service assembles them together. We should better document that only using X-Ray SDK to create subsegments inside Lambda context and thank you for your suggestions.

**Comment by ashleymercer** [comment]
> We should better document that only using X-Ray SDK to create subsegments inside Lambda context and thank you for your suggestions

Yep, it would be awesome if this could be added to the documentation - definitely caused a bit of head-scratching here! Thanks for your help, I'll go ahead and close this ticket.
