### ISSUE TITLE
Unable to reuse an existing trace ID when beginning a new segment in Lambda

### ISSUE THREAD

**Issue by bvingerh** [aws/aws-xray-sdk-java#246]
I'm using aws-xray-recorder-sdk-core version 2.8.0

The lambda function I'm working on get invoked by a larger application consisting of a set of Lambda functions and SQS queues. One of these components initiates an XRay trace and passes on the Root Trace ID to all the other components. Each lambda is required to begin a new segment (separable computations in each lambda can optionally create a subsegment).

When using the Java SDK, creating a subsegment inside a segment triggers a bug; see #245. I worked around this by creating the subsegment manually, based on the implementation from `com.amazonaws.xray.contexts.LambdaSegmentContext`. However, the original implementation checks whether the current (sub)segment has a different Root Trace ID than the one specified in the `_X_AMZN_TRACE_ID` environment variable and if so, clears the current entity and starts a new subsegment under the Root Trace ID from the environment.
As a result, I lose all the tracing information of this specific lambda.

Is this behaviour a bug or is it intended? If it is intended, then how can I add (sub)segments to an existing, externally provided,  Root Trace ID from within a Java Lambda?

**Comment by willarmiros** [comment]
Hi @bvingerh,

Thanks for raising this. In Lambda, X-Ray has an integration where the Lambda service that is executing your function will generate a segment on your behalf when "Active Tracing" is enabled. Since the Lambda service creates and populates the segment, it is immutable by your function code, and you cannot begin a new segment in its place. See the [Lambda docs](https://docs.aws.amazon.com/lambda/latest/dg/services-xray.html) for more. We are also actively working on providing the ability to trace Lambdas triggered by SQS queues to ensure each request in a batch is traced independently and correctly, as you describe, which is being tracked here: https://github.com/aws/aws-xray-sdk-node/issues/208

So for now, what you're describing is the expected behavior and you cannot begin custom segments with given trace IDs in Lambda. We could be open to a PR for a workaround to allow segments to be created normally in Lambda, and as long as you disable Active Tracing you could have the experience you're describing. Otherwise I'm not sure we'll have the bandwidth to add such a workaround before the feature I linked above is released.

**Comment by bvingerh** [comment]
Hi @willarmiros,

A collegue pointed me to "Active Tracing" as well, but according to the AWS Lambda Console, Active Tracing is not enabled on the deployed lambda. So I was not expecting a Segment to be created by the service.

For now I've worked around both problems by copying and adjusting the `LambdaSegmentContext#beginSubsegment` implementation so that I am able to create a custom Segment and add Subsegments to it from within my lambda.

When I have a moment I'll try to fit my solution in a PR.

**Comment by willarmiros** [comment]
Right, so the X-Ray SDK doesn't have any way of knowing whether Active Tracing is enabled or not, we can only detect whether we're in a Lambda environment or not. So we could allow for segments to be created and sent, it's just that they'd be duplicates if "Active Tracing" is also enabled. 

There's also the question of context behavior - in a normal environment, if you attempt to begin a subsegment with no active segment, you get a context missing exception. In Lambda, we assume the Lambda-created segment will be the parent so you can (and must) create subsegments without creating a segment first. If we add the ability you're describing, I suppose we'll allow both - if a subsegment without a parent is created, we assume "Active Tracing" is enabled and there will be a parent segment created by Lambda. If the function code creates a segment, we assume "Active Tracing" is disabled and parent all subsequent subsegments to the user-created segment.

Glad you've got a workaround working in the meantime :)

**Comment by bvingerh** [comment]
A solution for allowing the X-Ray SDK to know whether or not Active Tracing is set would be for Lambda to set the `_X_AMZN_TRACE_ID` environment variable to the relevant Root Trace ID when Active Tracing is on, and not setting the environment variable when Active Tracing is not enabled. That at least was my initial expectation.
Unless of course there is a valid reason for having a Root Trace ID available, even when Active Tracing is disabled?

**Comment by willarmiros** [comment]
The main reason is that when Active Tracing is disabled, the Lambda still acts in "pass through" mode where it just passively propagates any received trace header, but doesn't create a segment or sampling decision for itself. So say there was a APIGW trigger (with X-Ray enabled) in front of Lambda A (with active tracing disabled), and then Lambda A calls some other Lambda B (with active tracing enabled), the service map would be:

```
APIGW -> Lambda B
```

So in that case, we need the `_X_AMZN_TRACE_ID` to propagate to Lambda B even though Active tracing is disabled in Lambda A.
