### ISSUE TITLE
SNS-SQS Tracing

### ISSUE THREAD

**Issue by okhuz** [aws/aws-xray-sdk-java#298]
Hi we are trying utilize tracing in our spring boot application with X-Ray. I have configured my SNS with the following:

```
return AmazonSNSClientBuilder.standard()
            .withRegion(awsRegion)
            .withCredentials(awsCredentialProvider)
            .withRequestHandlers(snsFifoMessageGroupIdHandler, new TracingHandler(AWSXRay.getGlobalRecorder()))
```

I can see traces when my service sends a SNS message. But that SNS is also propagating messages to SQS's according to each queues filter. I can see the messages are filling the queues but I don't see SNS and SQS connection in AWS X-Ray console. I should have seen SQS but it is not in there. Am I doing some configuration mistakes?

**Comment by wangzlei** [comment]
Hi,

Both SNS and SQS are tracing passive mode, which means they don't generate real segments, SNS and SQS just pass through trace id from upstream to downstream.

When your application instruments SNS client, it creates a (sub)segment represent SNS client. Through this client segment, XRay will infer that there would be a SNS service in downstream, so, XRay service creates a virtual SNS node for better user experience. You can open the `raw data` of trace, find the virtual SNS service segment by searching keyword `inferred`.

That is also the reason you don't see SQS node because XRay service is not able to infer the second one since there are 2 consecutive passive mode services. If the system structure is active -> passive1 -> passive2, you only get active -> passive1 in XRay console. But if the system structure is active1 -> passive1 -> active2 -> passive2, you can see the full map. For example: Application on EC2 -> SNS -> Lambda -> SQS.

**Comment by okhuz** [comment]
Got it, thanks @wangzlei it was confusing at first. Now we are going to do whole manual tracing with begin and end segments with propagating the trace and segment ids in the message itself. I am closing this issue, thanks for clarification.
