### ISSUE TITLE
TransferManagerBuilder: S3 is not displayed on Service Map

### ISSUE THREAD

**Issue by DmPanov** [aws/aws-xray-sdk-java#37]
S3 does not get displayed on Service Map when accessed using `com.amazonaws.services.s3.transfer.TransferManagerBuilder#upload`.
Version of sdk: `com.amazonaws:aws-java-sdk-s3:1.11.271`

**Comment by luluzhao** [comment]
Hello @DmPanov ,

Currently, we only support creating additional nodes in the service map for S3, DynamoDB and SQS. `TransferManager` and `S3` are two separate classes and they all have their own constructors. In order to show S3 node, you have to explicitly pass S3 client when you create an instance of `TransferManager`.  Here I attached a code snippet for your reference. 

```
AmazonS3 client = AmazonS3ClientBuilder.standard()
                .withRegion("us-east-1")
                .withRequestHandlers(new TracingHandler(AWSXRay.getGlobalRecorder()))
                .build();
TransferManager transferManager = TransferManagerBuilder.standard().withS3Client(client).build();
try {
    Copy xfer = transferManager.copy("source_bucket", "source_key", "target_bucket", "target_key");
} catch (AmazonServiceException e) {
    System.err.println(e.getErrorMessage());
}
```

Feel free to contact me if you have any other questions.
