### ISSUE TITLE
How to add X-Amzn-Trace-Id in logger log4j. #Spring #microservice

### ISSUE THREAD

**Issue by prasad8mhatre** [aws/aws-xray-sdk-java#67]
Like Spring sleuth trace id (X-B3-TraceId), i want to put inside the logger format.
How to add X-Amzn-Trace-Id into logger? 
This will enable to watch the request related logs in cloudwatch as in xray, we dont see logs information when we search for trace id.

**Comment by chrisradek** [comment]
@prasad8mhatre 
If you have access to the global AWS X-Ray recorder (`AWSXRay.getGlobalRecorder()`), you can call `AWSXRay.getGlobalRecorder().currentTraceId().toString()` within your code to get the current trace id. 

The only prerequisite would be that the AWSXRayServletFilter has already processed the X-Amzn-Trace-Id for the request you're processing. The ServletFilter will check if the incoming request has the X-Amzn-Trace-Id header and create a segment using that id, or will generate a new Trace Id otherwise.

If you only want to log the trace id if a request is sampled, then you can grab the current segment from the recorder and check if it is sampled first:
```
AWSXRay.getGlobalRecorder().getCurrentSegment().isSampled());
```

**Comment by haotianw465** [comment]
Closing. Please feel free to provide extra comments or open a new issue should more help or suggestion needed.
