### ISSUE TITLE
AWSXRay Config not respecting AWS_XRAY_DAEMON_ADDRESS or system property (Springboot)

### ISSUE THREAD

**Issue by jonesg504** [aws/aws-xray-sdk-java#79]
I am trying to get Xray setup in a springboot project of mine and no matter how I try to set the Daemon address, it always give this error: 
```
Encountered error polling GetSamplingRules: 
com.amazonaws.SdkClientException: Unable to execute HTTP request: Connect to 127.0.0.1:2000 [/127.0.0.1] failed: Connection refused (Connection refused)
```

Im running the Springboot service on EKS, I have set the Enviroment variable in the deployment.yaml: 
```
env:
- name: AWS_XRAY_DAEMON_ADDRESS 
  value: xray-service.default
```

I have also tried setting that enviroment variable when the docker image is built with ENV in the Dockerfile

I also tried setting 
```
com:
  amazonaws:
    xray:
      emitters:
        daemonAddress: xray-service.default
``` 
in the application.yml as well as setting a `<systemPropertyVariables>` in the pom.xml.

Is there another configuration I need to set somewhere? 

UPDATE:
Turns out I was missing the port for the kubernetes service (2000), now its sending traces to the daemon, however I still get an error:
```
Encountered error polling GetSamplingRules: 
com.amazonaws.SdkClientException: Unable to execute HTTP request: Connect to xray-service:2000 [xray-service/HIDDEN-IP, xray-service/HIDDEN-IP] failed: Connection refused (Connection refused) 
```

**Comment by awssandra** [comment]
Hi jonesg504,

So this is a change to the X-Ray Daemon 3.x and the release of the X-Ray Service [sampling rules](https://docs.aws.amazon.com/xray/latest/devguide/xray-console-sampling.html).

Now, the SDK (and Daemon) uses both a UDP (for sending the segments) and a TCP port (to proxy the sampling rules from the X-Ray service to the SDK). [AWS_XRAY_DAEMON_ADDRESS](https://docs.aws.amazon.com/xray/latest/devguide/xray-sdk-java-configuration.html#xray-sdk-java-configuration-envvars) can be set in the format of "udp:address:port tcp:address:port". Since you do not have this format, "xray-service:2000" is being used for both.

Configuring both the UDP and TCP ports for your kubernetes service should remove the error. If you wish to rely on the local sampling the SDK provides, you can [configure the SDK to do so](https://docs.aws.amazon.com/xray/latest/devguide/xray-sdk-java-configuration.html#xray-sdk-java-configuration-sampling).

Hope this helps!
Sandra
